# Configuração do Hyprlock (Bloqueio de Tela)
# Documentação: https://wiki.hyprland.org/Hypr-Ecosystem/Hyprlock/

# Plano de fundo
background {
    monitor =
    path = /home/ito/Imagens/.wallpaper_dark.jpg
    # color = rgba(38, 156, 182, 0.8)

    # Blur
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Campo de entrada
input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2

    # Configuração dos pontos (dots) de senha
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1

    # Cores do campo
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(68, 68, 68)

    # Comportamento de fade
    fade_on_empty = false
    fade_timeout = 0

    # Texto e Estética
    placeholder_text = <span foreground='##444444' font='Roboto Medium 9'></span>
    hide_input = false
    rounding = 8

    # Cores de status (Sucesso/Erro)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300   # Transição em ms entre cor normal e falha

    # Configurações de Lock (Caps/Num)
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1     # -1 não altera a cor externa
    invert_numlock = false

    # Posicionamento
    position = 0, -20
    halign = center
    valign = center
}

# Rótulo de data
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +'%d de %B')"
    color = rgb(68, 68, 68)
    font_size = 15
    font_family = Roboto Bold

    position = 0, 75
    halign = center
    valign = center
}

# Rótulo de hora
label {
    monitor =
    text = cmd[update:1000] echo -e "$(
