# Configuração do Hyprlock (Bloqueio de Tela)
# Documentação: https://wiki.hyprland.org/Hypr-Ecosystem/Hyprlock/

### PLANO DE FUNDO (BACKGROUND) ###
background {
    monitor =
    path = /home/ito/Imagens/.wallpaper.jpg
    # color = rgba(38, 156, 182, 0.8)

    # Opções de desfoque (Blur)
    blur_passes = 2        # 0 desativa o desfoque
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

### CAMPO DE ENTRADA (INPUT FIELD) ###
input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2

    # Configuração dos pontos (dots) de senha
    dots_size = 0.3         # Escala da altura (0.2 - 0.8)
    dots_spacing = 0.2      # Escala do tamanho absoluto (0.0 - 1.0)
    dots_center = true
    dots_rounding = -1      # -1 círculo padrão, -2 segue arredondamento do campo

    # Cores do campo
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(68, 68, 68)

    # Comportamento de fade
    fade_on_empty = false
    fade_timeout = 0        # Milissegundos antes do fade acionar

    # Texto e Estética
    placeholder_text = <span foreground='##444444' font='Roboto Medium 9'></span>
    hide_input = false
    rounding = 8

    # Cores de status (Sucesso/Erro)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300   # Transição em ms entre cor normal e falha

    # Configurações de Lock (Caps/Num)
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1     # -1 não altera a cor externa
    invert_numlock = false

    # Posicionamento
    position = 0, -20
    halign = center
    valign = center
}

### RÓTULO DE DATA (DATE LABEL) ###
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +'%d de %B')"
    color = rgb(68, 68, 68)
    font_size = 15
    font_family = Roboto Bold

    position = 0, 75
    halign = center
    valign = center
}

### RÓTULO DE HORA (TIME LABEL) ###
label {
    monitor =
    text = cmd[update:1000] echo -e "$(
