conky.config = {
    xinerama_head = 0,
    alignment = 'top_right',
    gap_x = 40,
    gap_y = 40,
    out_to_x = true,
    out_to_wayland = false,
    background = false,
    double_buffer = true,
    font = 'Roboto + Noto Sans CJK SC:style=Bold:size=10',
    use_xft = true,
    minimum_width = 290,
    minimum_height = 300,
    own_window = true,
    own_window_type = 'desktop',
    own_window_class = 'Conky',
    own_window_transparent = false,
    own_window_argb_visual = true,
--  own_window_argb_value = 0,
    own_window_colour = '#253034',
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    default_color = '#e8e8e8',
    color1 = '#78909c',
    draw_borders = false,
    draw_outline = false,
    draw_shades = false,
    draw_graph_borders = false,
    cpu_avg_samples = 2,
    net_avg_samples = 2,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
}
conky.text = [[
${color1}${font ConkySymbols:size=11}${goto 7}t${font} ${voffset -4}$hr${color}
${color1}${goto 30}Kernel ${color}$kernel ${alignr}${uptime_short}
${color1}${font MaterialIcons:size=12}${font} ${voffset -4}$hr${color}
${color1}${goto 30}${color}${freq_g 1}GHz ${alignr}${cpu cpu0}% ${color1}${cpubar cpu0 4,50}
${color1}${goto 30}${color}${freq_g 2}GHz ${alignr}${cpu cpu1}% ${color1}${cpubar cpu1 4,50}
${color1}${goto 30}${color}${freq_g 3}GHz ${alignr}${cpu cpu2}% ${color1}${cpubar cpu2 4,50}
${color1}${goto 30}${color}${freq_g 4}GHz ${alignr}${cpu cpu3}% ${color1}${cpubar cpu3 4,50}
${color1}${goto 30}${cpugraph cpu0 45,240 }
${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${color1}${goto 30}CPU ${color}${exec sensors | grep 'CPU' | awk 'NR==1{print $2}'} ${alignr}${color1}PCH ${color}${exec sensors | grep 'temp1' | awk 'NR==1{print $2}'}
${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${color1}${goto 30}RAM ${color}$mem / $memmax ${alignr}$memperc% ${color1}${membar 4,50}
${color1}${goto 30}SWAP ${color}$swap / $swapmax ${alignr}$swapperc% ${color1}${swapbar 4,50}
${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${color1}${goto 30}SSD ${color}${fs_used /} / ${fs_size /} ${alignr}${fs_used_perc /}% ${color1}${fs_bar 4,50 /}
${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${if_match ${battery_percent BAT0}<20}${color #ff4444}${else}${color1}${endif}${goto 30}${color1}BAT ${color #e8e8e8}1 ${color}${exec ~/.config/conky/bat_time.sh BAT0} ${alignr}${battery_percent BAT0}% ${if_match ${battery_percent BAT0}<20}${color #ff4444}${else}${color1}${endif}${battery_bar 4,50 BAT0}${color}
${if_match ${battery_percent BAT1}<20}${color #ff4444}${else}${color1}${endif}${goto 30}${color1}BAT ${color #e8e8e8}2 ${color}${exec ~/.config/conky/bat_time.sh BAT1} ${alignr}${battery_percent BAT1}% ${if_match ${battery_percent BAT1}<20}${color #ff4444}${else}${color1}${endif}${battery_bar 4,50 BAT1}${color}
${if_match "${exec ~/.config/conky/bt_battery.sh}"!=""}${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${color1}${goto 30}${execpi 10 ~/.config/conky/bt_line.sh}
${endif}${color1}${font MaterialIcons:size=12}${font} ${voffset -5}$hr${color}
${color1}${goto 30}WLAN ${color}${wireless_link_qual_perc wlp3s0}% ${color1}${alignr}${wireless_link_bar 4,50 wlp3s0}
${color1}${goto 30}${font MaterialIcons:size=10}${font} ${color}${downspeed wlp3s0} ${alignr}${totaldown wlp3s0}
${color1}${goto 30}${font MaterialIcons:size=10}${font} ${color}${upspeed wlp3s0} ${alignr}${totalup wlp3s0}

$alignc
]]
